// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentAttendanceTrackingApp.Data;

#nullable disable

namespace StudentAttendanceTrackingApp.Data.Migrations
{
    [DbContext(typeof(SATDbContext))]
    [Migration("20240902195331_alldata")]
    partial class alldata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentAttendanceTrackingApp.Data.Entities.ApiUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiUsers", "satapp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Tech Solutions",
                            CreaDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Password = "password123",
                            Phone = "+1234567890",
                            UserName = "jdoe"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Innovatech",
                            CreaDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alicesmith@example.com",
                            FirstName = "Alice",
                            IsDeleted = false,
                            LastName = "Smith",
                            Password = "securepass456",
                            Phone = "+0987654321",
                            UserName = "asmith"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Future Tech",
                            CreaDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bobmiller@example.com",
                            FirstName = "Bob",
                            IsDeleted = false,
                            LastName = "Miller",
                            Password = "mypassword789",
                            Phone = "+1122334455",
                            UserName = "bmiller"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Tech Innovators",
                            CreaDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charliejohnson@example.com",
                            FirstName = "Charlie",
                            IsDeleted = false,
                            LastName = "Johnson",
                            Password = "pass1234",
                            Phone = "+6677889900",
                            UserName = "cjohnson"
                        },
                        new
                        {
                            Id = 5,
                            Company = "NextGen Tech",
                            CreaDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dianadavis@example.com",
                            FirstName = "Diana",
                            IsDeleted = false,
                            LastName = "Davis",
                            Password = "password321",
                            Phone = "+4455667788",
                            UserName = "ddavis"
                        });
                });

            modelBuilder.Entity("StudentAttendanceTrackingApp.Data.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Lesson", "satapp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6638),
                            IsDeleted = false,
                            Name = "Matematik"
                        },
                        new
                        {
                            Id = 2,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6648),
                            IsDeleted = false,
                            Name = "Fizik"
                        },
                        new
                        {
                            Id = 3,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6650),
                            IsDeleted = false,
                            Name = "Kimya"
                        },
                        new
                        {
                            Id = 4,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6651),
                            IsDeleted = false,
                            Name = "Biyoloji"
                        },
                        new
                        {
                            Id = 5,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6652),
                            IsDeleted = false,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 6,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6657),
                            IsDeleted = false,
                            Name = "Coğrafya"
                        },
                        new
                        {
                            Id = 7,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6658),
                            IsDeleted = false,
                            Name = "İngilizce"
                        },
                        new
                        {
                            Id = 8,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6659),
                            IsDeleted = false,
                            Name = "Edebiyat"
                        },
                        new
                        {
                            Id = 9,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6660),
                            IsDeleted = false,
                            Name = "Bilgisayar Bilimleri"
                        },
                        new
                        {
                            Id = 10,
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(6663),
                            IsDeleted = false,
                            Name = "Beden Eğitimi"
                        });
                });

            modelBuilder.Entity("StudentAttendanceTrackingApp.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Students", "satapp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1981, 2, 16, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Eskişehir",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4899),
                            Email = "yağmur.tilbe.81@hotmail.com",
                            FirstName = "Yağmur",
                            IsDeleted = false,
                            LastName = "Tilbe"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1980, 11, 1, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Yalova",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4927),
                            Email = "kaan.tilbe.80@hotmail.com",
                            FirstName = "Kaan",
                            IsDeleted = false,
                            LastName = "Tilbe"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 12, 30, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Edirne",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4939),
                            Email = "hasan.yıldız.00@hotmail.com",
                            FirstName = "Hasan",
                            IsDeleted = false,
                            LastName = "Yıldız"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2005, 9, 28, 21, 0, 0, 0, DateTimeKind.Utc),
                            City = "Zonguldak",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4949),
                            Email = "utku.yurt.05@hotmail.com",
                            FirstName = "Utku",
                            IsDeleted = false,
                            LastName = "Yurt"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2000, 12, 24, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Kilis",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4959),
                            Email = "buğra.aksu.00@hotmail.com",
                            FirstName = "Buğra",
                            IsDeleted = false,
                            LastName = "Aksu"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1970, 12, 2, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Bilecik",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4973),
                            Email = "veli.aksu.70@hotmail.com",
                            FirstName = "Veli",
                            IsDeleted = false,
                            LastName = "Aksu"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1999, 3, 9, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Muş",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4984),
                            Email = "hakan.derici.99@hotmail.com",
                            FirstName = "Hakan",
                            IsDeleted = false,
                            LastName = "Derici"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1984, 11, 6, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Bartın",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(4993),
                            Email = "osman.kaya.84@hotmail.com",
                            FirstName = "Osman",
                            IsDeleted = false,
                            LastName = "Kaya"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2000, 7, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            City = "Burdur",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5003),
                            Email = "buğra.aslan.00@hotmail.com",
                            FirstName = "Buğra",
                            IsDeleted = false,
                            LastName = "Aslan"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1975, 6, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            City = "Ankara",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5081),
                            Email = "sedef.yurt.75@hotmail.com",
                            FirstName = "Sedef",
                            IsDeleted = false,
                            LastName = "Yurt"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2010, 1, 21, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Samsun",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5091),
                            Email = "osman.derici.10@hotmail.com",
                            FirstName = "Osman",
                            IsDeleted = false,
                            LastName = "Derici"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2006, 6, 26, 21, 0, 0, 0, DateTimeKind.Utc),
                            City = "Kilis",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5102),
                            Email = "yeşim.deniz.06@hotmail.com",
                            FirstName = "Yeşim",
                            IsDeleted = false,
                            LastName = "Deniz"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1978, 8, 18, 21, 0, 0, 0, DateTimeKind.Utc),
                            City = "Bitlis",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5111),
                            Email = "barış.yar.78@hotmail.com",
                            FirstName = "Barış",
                            IsDeleted = false,
                            LastName = "Yar"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1987, 11, 19, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Adıyaman",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5120),
                            Email = "hakan.yıldız.87@hotmail.com",
                            FirstName = "Hakan",
                            IsDeleted = false,
                            LastName = "Yıldız"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1994, 11, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            City = "Eskişehir",
                            CreaDate = new DateTime(2024, 9, 2, 19, 53, 30, 455, DateTimeKind.Utc).AddTicks(5130),
                            Email = "kaan.soy.94@hotmail.com",
                            FirstName = "Kaan",
                            IsDeleted = false,
                            LastName = "Soy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
